function writeHeader() {writeHeader(false);}

function writeHeader(virtuozo) {
    document.write('<a target=_blank href=http://www.parallels.com/plesk/ title='Plesk&trade;' class=topLogo>')
    document.write('<img src=/img/common/def_plesk_logo.gif name=logo title='Plesk&trade;'/></a>');
    document.write('<div id=topTxtBlock><div id=topBgBlock>');
    document.write('<span id=topCopyright><a href=http://www.parallels.com target=_blank>&copy; Copyright 1999-2008, Parallels All rights reserved</a></span>');
    if (virtuozo) {document.write('<span id=topTxtBanner><a href=http://www.virtuozzo.com/en/splandingpage/ target=_blank>Discover <b>Parallels<br/>Virtuozzo Containers</b></a></span>');}
    document.write('</div>');
    document.write('<span id=topRightLogo><a href=http://www.parallels.com target=_blank><img src="/img/common/def_parallels_logo.gif"></img></a></span></div>');
}

function writeFooter() {writeFooter(true);}

function writeFooter(virtuozzo) {
    document.write('<div class=footDescription>This page is autogenerated by <a target=_blank href="http://www.parallels.com/en/products/plesk/">Parallels<sup>&reg;</sup>Plesk Control Panel</a></div>');
    document.write('<div class=poweredBy><a target=_blank href="http://www.parallels.com"><img src="/img/common/parallels_powered.gif" title="Plesk&trade;"/></a></div>');
    if (virtuozzo) {}
}

function writeCopyFlag() {document.write('<script language=javascript type=text/javascript src="http://' + location.hostname + ':8880/javascript/promo-flags.js.php"></' + 'script>\n');}